In [1]:
import numpy as np
import time
import sys

In [2]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [6]:
a[2]


3

In [7]:
l=range(1000)
print(sys.getsizeof(5)*len(l))
array =np.arange(1000)
print(array.size*array.itemsize)

28000
8000


In [9]:
SIZE = 1000000
l1= range(SIZE)
l2= range(SIZE)
start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print ("Python list: ", ((time.time()-start)*1000))  

Python list:  140.47527313232422


In [10]:
SIZE = 1000000
a1=np.arange(SIZE)
a2=np.arange(SIZE) 
start = time.time()
result = a1+a2
print ("Numpy take: ", ((time.time()-start)*1000))

Numpy take:  5.523204803466797


In [13]:
a1= np.array([1,2,3])
a2= np.array([3,4,5]) 
a1+a2

array([4, 6, 8])

In [14]:
a2-a1

array([2, 2, 2])

In [15]:
a1.dot(a2)

26

In [16]:
a= np.array([3,4,5])
a.ndim 

1

In [17]:
a= np.array([[1,2],[3,4],[5,6]])
a.ndim

2

In [18]:
a= np.array([[1,2],[3,4],[5,6]])
a.itemsize

8

In [19]:
a= np.array([[1,2],[3,4],[5,6]] , dtype=np.float64)
a.itemsize

8

In [20]:
a.dtype

dtype('float64')

In [21]:
a= np.array([[1,2],[3,4],[5,6]] , dtype=np.int64)
a.itemsize

8

In [22]:
a.dtype

dtype('int64')

In [27]:
a, a.size, a.shape

(array([[1, 2],
        [3, 4],
        [5, 6]]), 6, (3, 2))

In [28]:
a= np.array([[1,2],[3,4],[5,6]] , dtype=complex)
a.itemsize

16

In [29]:
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [30]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
l= range(5)
l

range(0, 5)

In [34]:
l[1], l[3]

(1, 3)

In [37]:
np.arange(1,5,2)

array([1, 3])

In [38]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [39]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [40]:
a= np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [42]:
a.shape

(3, 2)

In [43]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [50]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

a

In [53]:
a.min()
a.max()

6

In [54]:
a.sum()

21

In [55]:
a.sum(axis=0)

array([ 9, 12])

In [56]:
a.sum(axis=1)

array([ 3,  7, 11])

In [58]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [59]:
np.std(a)

1.707825127659933

In [60]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
a

array([[1, 2],
       [3, 4]])

In [61]:
b

array([[5, 6],
       [7, 8]])

In [62]:
a+b

array([[ 6,  8],
       [10, 12]])

In [63]:
a*b

array([[ 5, 12],
       [21, 32]])

In [64]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [65]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [66]:
n=[6,7,8]
n[0:2]

[6, 7]

In [67]:
n[-1]

8

In [68]:
a=np.array([6,7,8])
a[0:2]

array([6, 7])

In [69]:
a=np.array([[6,7,8],[1,2,3],[9,3,2]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [70]:
a[1,2]

3

In [71]:
a[0:2,2]

array([8, 3])

In [72]:
a[-1,0:2]

array([9, 3])

In [73]:
for row in a : 
  print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [74]:
for cell in a.flat:
  print(cell)

6
7
8
1
2
3
9
3
2


In [75]:
a=np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [76]:
b=np.arange(6,12).reshape(3,2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [77]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [78]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [79]:
a=np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [80]:
np.hsplit(a,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [81]:
result=np.hsplit(a,3)
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [82]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [83]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [84]:
result=np.vsplit(a,2)
result[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [85]:
result[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [86]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [87]:
b=a>4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [88]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [89]:
a[b]=-1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [90]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [91]:
for cell in a.flatten() :
  print (cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [92]:
for x in np.nditer(a,order='C') :
  print (x)

0
1
2
3
4
5
6
7
8
9
10
11


In [93]:
for x in np.nditer(a,order='F') :
  print (x)

0
4
8
1
5
9
2
6
10
3
7
11


In [94]:
for x in np.nditer(a,order='F', flags= ['external_loop']) :
  print (x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [95]:
for x in np.nditer(a,op_flags= ['readwrite']) :
 x[...]= x*x
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [96]:
b=np.arange(3,15,4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [97]:
for x,y in np.nditer([a,b]) :
  print (x,y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11
